### PR TITLE
Add photo-screen-saver to "Built on Electron" section.

### PR DESCRIPTION
**Pull request by RandScullard**

### CODE REVIEW

**Comment by kevinsawicki** [comment]
@RandScullard there is a new community page at http://electron.atom.io/community that launched as part of Electron 1.0 in #238

That page is powered by https://github.com/sindresorhus/awesome-electron so any projects add there will eventually show up on the page.

So I'm going to close this out here, thanks!

**Comment by RandScullard** [comment]
@kevinsawicki That new site looks great -- thanks for pointing me to it. However, I could use some guidance. That Community page has sections for Tools, Boilerplates, Components, and Videos, and my project is none of these. It's just a little open-source app built on Electron. It doesn't look like it belongs on the Apps page either, since those appear to be commercial apps with, you know, logos and marketing and stuff. Any hints?

**Comment by kevinsawicki** [comment]
> Any hints?

Does your app have an icon? Open source apps are totally find on the apps page, there are many there already, the only requirement to be there is to have a custom icon.

**Comment by RandScullard** [comment]
It does now. ;) 
OK, I opened pull request #250 to do this the (hopefully) right way. Thanks for your help!

**Pull request closed without merging**
