### PR TITLE
Added Mattermost to Application List

### PR DESCRIPTION
**Pull request by OFmarting**
The [Mattermost Desktop Application](https://github.com/mattermost/desktop) is using Electron.

### CODE REVIEW

**Comment by jlord** [comment]
Awesome, are you affiliated with the project? Just want to make sure we have an OK to add from that side.

**Comment by jlord** [comment]
Closing for now, can re-open with more information later.

**Comment by it33** [comment]
This is [it33](https://github.com/it33) from the Mattermost project, all fine to add, @jlord 

Sorry for late reply, we were debating which icon to use, what's there is fine,

**Comment by jlord** [comment]
Awesome, thanks!

**Pull request merged**
