### PR TITLE
Improve contrast

### LINKED ISSUE #746: Improve color contrast
@kuychaco + @kevinsawicki's tool spit out a huge list where color contrast isn't accessible: https://gist.github.com/kuychaco/f4198e0cf2e1d671fd042cd78a339c39

Would be great to shrink the list a bit.

### PR DESCRIPTION
**Pull request by simurai**
This PR makes sure the colors have enough contrast.

- [x] `/` Home
- [x] `/docs/`
- [x] `/blog/`
- [x] `/community/`
- [x] `/apps/`
- [x] `/userland/`
- [x] `/releases/`
- [x] `/contact/`

Closes #746 

Audit violations due to color contrast

build__1530_-_electron_electron_atom_io_-_travis_ci

### CODE REVIEW

**Comment by simurai** [comment]
Tested these changes with the home page in the new "Audits" of Chrome Canary. It's now 💯 % accessible.

image

**Comment by kuychaco** [comment]
Sweet! Thanks @simurai 😄 

Looks like we're down to just a few more under `http://127.0.0.1:4000/docs/api/`. Think they're worth adjusting in order to pass the audit?

```
Accessibility
http://127.0.0.1:4000/docs/api/auto-updater ✗ color-contrast - Background and foreground colors have a sufficient contrast ratio.
   Element has insufficient color contrast of 4.47 (foreground color: #777777, background color: #ffffff, font size: 12.0pt, font weight: normal)
     <p>Enable apps to automatically update themselves.</p>

Accessibility
http://127.0.0.1:4000/docs/api/crash-reporter ✗ color-contrast - Background and foreground colors have a sufficient contrast ratio.
   Element has insufficient color contrast of 4.47 (foreground color: #777777, background color: #ffffff, font size: 12.0pt, font weight: normal)
     <p>Submit crash reports to a remote server.</p>
   Element has insufficient color contrast of 4.37 (foreground color: #008080, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="na">productName</span>
     <span class="na">companyName</span>
     <span class="na">submitURL</span>
     <span class="na">uploadToServer</span>
     <span class="na">ELECTRON_INTERNAL_CRASH_SERVICE</span>
     <span class="na">env</span>
     <span class="na">detached</span>
   Element has insufficient color contrast of 3.2 (foreground color: #009999, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="mi">1</span>

Accessibility
http://127.0.0.1:4000/docs/api/menu ✗ color-contrast - Background and foreground colors have a sufficient contrast ratio.
   Element has insufficient color contrast of 4.47 (foreground color: #777777, background color: #ffffff, font size: 12.0pt, font weight: normal)
     <p>Create native application menus and context menus.</p>
   Element has insufficient color contrast of 4.37 (foreground color: #008080, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="na">label</span>
     <span class="na">submenu</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">type</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">label</span>
     <span class="na">submenu</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">type</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">type</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">submenu</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">submenu</span>
     <span class="na">label</span>
     <span class="na">label</span>
     <span class="na">submenu</span>
     <span class="na">role</span>
     <span class="na">type</span>
     <span class="na">role</span>
     <span class="na">submenu</span>
     <span class="na">type</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">type</span>
     <span class="na">role</span>
     <span class="na">type</span>
     <span class="na">label</span>
     <span class="na">submenu</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">role</span>
     <span class="na">type</span>
     <span class="na">role</span>
     <span class="na">label</span>
     <span class="na">type</span>
     <span class="na">label</span>
     <span class="na">type</span>
     <span class="na">checked</span>
     <span class="na">label</span>
     <span class="na">id</span>
     <span class="na">label</span>
     <span class="na">id</span>
     <span class="na">label</span>
     <span class="na">id</span>
     <span class="na">position</span>
     <span class="na">label</span>
     <span class="na">id</span>
     <span class="na">label</span>
     <span class="na">id</span>
     <span class="na">label</span>
     <span class="na">position</span>
     <span class="na">label</span>
     <span class="na">position</span>
     <span class="na">label</span>
     <span class="na">position</span>
     <span class="na">label</span>
     <span class="na">position</span>
     <span class="na">label</span>
     <span class="na">position</span>
     <span class="na">label</span>
     <span class="na">position</span>
   Element has insufficient color contrast of 2.65 (foreground color: #999988, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="c1">// Edit menu</span>
     <span class="c1">// Window menu</span>
     <span class="c">&lt;!-- index.html --&gt;</span>
   Element has insufficient color contrast of 3.2 (foreground color: #009999, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="mi">1</span>
     <span class="mi">3</span>
   Element has insufficient color contrast of 3.8 (foreground color: #0086b3, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="nb">window</span>

Accessibility
http://127.0.0.1:4000/docs/api/content-tracing ✗ color-contrast - Background and foreground colors have a sufficient contrast ratio.
   Element has insufficient color contrast of 4.47 (foreground color: #777777, background color: #ffffff, font size: 12.0pt, font weight: normal)
     <p>Collect tracing data from Chromium’s content module for finding performance bottlenecks and slow operations.</p>
   Element has insufficient color contrast of 4.37 (foreground color: #008080, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="na">categoryFilter</span>
     <span class="na">traceOptions</span>
   Element has insufficient color contrast of 3.2 (foreground color: #009999, background color: #f5f5f5, font size: 10.2pt, font weight: normal)
     <span class="mi">5000</span>
```

**Comment by simurai** [comment]
> Think they're worth adjusting in order to pass the audit?

Ok, should all be fixed except for these [syntax highlighting](https://github.com/electron/electron.atom.io/blob/gh-pages/_sass/_highlight.scss) colors. Maybe we can find another theme that passes?

**Comment by simurai** [comment]
@kuychaco If you wanna give it another run, changed the syntax highlighting.

Before

image

After

image

Comments would be much less subtle.

**Comment by kuychaco** [comment]
Awesome! Thanks so much @simurai ✨ 

I saw some more errors when I ran locally. I'm gonna marge this branch into the`lighthouse` branch so that CI will run and you can see the failures

**Pull request merged**
