### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by adwankar**
Sencha Electron products

### CODE REVIEW

**Comment by Haacked** [comment]
What are these files for? Could you add a bit more context to this PR?

**Comment by adwankar** [comment]
Icons for Sencha's products using Electron

**Comment by Haacked** [comment]
@adwankar any reason you don't just add these to your existing PR here? https://github.com/electron/electron.atom.io/pull/528

**Comment by zeke** [comment]
Closing this out. @adwankar please go ahead and update the other PR: https://github.com/electron/electron.atom.io/pull/528

**Pull request closed without merging**
