### PR TITLE
Nav styles

### PR DESCRIPTION
**Pull request by zeke**
This PR updates the nav to dynamically change color based on the colors of the current app you're viewing. All colors have their contrast ratio tested in electron-apps, so they're guaranteed to be accessible.

screen shot 2017-11-13 at 8 10 18 am

screen shot 2017-11-13 at 8 09 34 am

screen shot 2017-11-13 at 8 09 58 am

cc @donokuda @simurai

### CODE REVIEW

**Comment by zeke** [comment]
An alternative way for Electron's branding/nav to "take a back seat" on these app pages,would be to make the nav background white with the Electron logo and nav links some faint grayish color.

**Comment by Toinane** [comment]
Cool idea, what about logo with multiple colors in?

**Comment by donokuda** [comment]
⚡️ Electrifying! ⚡️ 

This looks awesome. I'm not sure what the branding guidelines are for the website (and if changing the header color is okay), so this is something I'd like @simurai to chime in when he gets back.

That said, having the header match the custom link colors is  🌈 ✨ and feels more consistent overall as a result.

**Comment by zeke** [comment]
> what about logo with multiple colors in?

@Toinane the most "bold" color in the logo is selected. The implementation for that is here: https://github.com/zeke/pick-a-good-color and here: https://github.com/zeke/make-color-accessible

**Comment by zeke** [comment]
I'm gonna go ahead and ship this and If it's not well-received by the Electron maintainers group (or @simurai :)) we can roll it back.

**Comment by Toinane** [comment]
Okay cool, Thanks for the details :)!

**Pull request merged**
