### PR TITLE
Add Socialcast app

### PR DESCRIPTION
**Pull request by kparitosh**
This PR adds Socialcast to the Electron Apps list. Thanks!

Website: http://socialcast.com/

### CODE REVIEW

**Comment by zeke** [comment]
Thanks @kparitosh. I see the license is blank. Does this app have a license? If not, I would recommend omitting the `license` key.

**Comment by kparitosh** [comment]
@zeke Sure, let me get to you after checking with my legal/product team for the license. 
Appreciate your patience on this one. Thanks!

**Comment by jlord** [comment]
Closing for now. Feel free to re-open when you know about omitting or listing the license 👍

**Comment by kparitosh** [comment]
@jlord / @zeke I would be omitting the license key. I have already [pushed a commit](https://github.com/electron/electron.atom.io/commit/bb9666d6c8ec799acf38fe331c655c4bd9a79db7) to do that in my [forked branch](https://github.com/kparitosh/electron.atom.io). 

Can I re-open this PR!?(I am not getting an option to re-open and/or remove the label this from the Github UI) or should I create a fresh PR for it?

**Comment by jlord** [comment]
@kparitosh I reopened. Would you mind removing line `1289` also, since it is also empty? After that it looks good to go 👍

**Comment by kparitosh** [comment]
@jlord Thanks for re-opening the PR. I have removed all the empty keys as you suggested. 
Do let me know if there is anything else needed from my side. 

Thanks again for all your help on this!

**Pull request merged**
