### PR TITLE
Optimize icons

### PR DESCRIPTION
**Pull request by FradSer**
Compress with TinyPNG.

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Awesome, do you have any stats on the size difference this makes?

**Comment by FradSer** [comment]
@kevinsawicki No.

**Comment by FradSer** [comment]
How to solve the conflict?

**Comment by FradSer** [comment]
@kevinsawicki every PNG files are up to 50% smaller than before, and they were lossless.

**Comment by FradSer** [comment]
@kevinsawicki already solve the conflict.

**Pull request closed without merging**
