### PR TITLE
replace Jekyll with a Node server 🐢🚀

### PR DESCRIPTION
**Pull request by zeke**
🚧 DO NOT MERGE 🚧 

This PR replaces Jekyll with a Node server using Express.

Changes to this branch are auto-deployed to [electronjs.org](http://electronjs.org/).

## Reasons™

- **Developer Experience**. It should be fun and easy to work on the site, and Jekyll is not always up to that task. See #668 
- **Consistency in Tooling**. Nearly every project that the Electron team works on is written in JavaScript, and it is our language/ecosystem of expertise. Eliminating the Ruby dependency will make it easier for team members to work on the app, make more opportunities for code sharing across projects, and lower the barrier to entry for outside contributors from the community.
- **Server-y Things**. Using a web server will allow us to do things that a static site can't, like setting proper redirects for deprecated URLs or conditionally displaying content based on a browser's `Accept-Language` header. See #638 
- **Internationalization**. Eventually we'll be serving up content in different languages from [electron-i18n](https://github.com/electron/electron-i18n). This will require a level of performance and flexibility that simply isn't possible with Jekyll.
- **Flexibility**. As the site grows and improves, we want to have the option to support things like dynamic routes, forms that users can fill out, etc.

## Highlights

🌍  **Localized Content** - automated flow in and out of Crowdin means docs in any language!

📖  **Updated Documentation** - always fresh from the master branch.

💻 **Apps** - now categorized and each app has its own URL.

🔧 **Consistent Tooling** - goodbye ruby; node is everywhere.

🛰 **Dynamism**. running a webserver gives us dynamic routes, forms that users can fill out, etc.

🤖  **Automated Deployment** - greenkeeper and semantic-release ftw

## Progress

See the [project board](https://github.com/electron/electron.atom.io/projects/1).

### CODE REVIEW

**Comment by simurai** [comment]
Should [.node-version](https://github.com/electron/electron.atom.io/blob/neo/.node-version#L1) get updated or removed? When I `npm start`, I got

```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

After some googling I removed `.node-version` and am now using the latest `v8.2.1`, which seemed to fix it. Although I think I also did some other stuff, like it told me to `npm rebuild node-sass --force` and maybe more.

**Comment by zeke** [comment]
> Should [.node-version](https://github.com/electron/electron.atom.io/blob/neo/.node-version#L1) get updated or removed?

Yeah we can remove it.

> it told me to `npm rebuild node-sass --force`

To overcome the sass issue, I would say `rm -rf node_modules && npm i` should do it.

> Also, [CONTRIBUTING](https://github.com/electron/electron.atom.io/blob/neo/CONTRIBUTING.md#developing-the-site-locally) probably is out of date.

Yes there is still lots of leftover stuff from the Jekyll site. I just added a note about this to the checklist above.

**Comment by simurai** [comment]
> zeke had a problem deploying to electron-website

Did I break it? The app page should now look like:

voila_capture 2017-08-15_5-26-27_pm

**Comment by zeke** [comment]
Thanks for jumping in, @simurai. This looks rad. I'll figure out what's up tomorrow. 💤

**Comment by zeke** [comment]
@simurai it wasn't you! It was a regression in primer-breadcrumb, which is now pinned to an older version.

It was also some npm/github shenanigans in [electron-i18n](https://github.com/electron/electron-i18n/pull/63). I just pushed up some changes and we should see it reflected on electronjs.org soon. 🤞

**Comment by zeke** [comment]
I'm going to close this, as this PR is never actually going to land on the `gh-pages` branch. Also we've already made `neo` the (temporary) default branch, so any new PRs will use it as the target. I'll post a link to the blog post when the new site officially drops.

**Comment by zeke** [comment]
It's live: electronjs.org/blog/new-website

**Pull request closed without merging**
