### PR TITLE
Add healthi app

### PR DESCRIPTION
**Pull request by pablopunk**
I'm the developer of this simple app that runs in your mac's topbar, checking the health of your battery.

### CODE REVIEW

**Comment by zeke** [comment]
Nice!

The cask install is not working for me:

```
Error: No available Cask for healthi
Error: nothing to install
```

I did a `brew tap caskroom/cask` but that didn't help.

**Comment by pablopunk** [comment]
@zeke yeah I pushed it to cask yesterday. It's merged but I don't know when it's being actually pulled to users.

What I did to make sure it works was:
```shell
cd "$(brew --repository)"/Library/Taps/caskroom/homebrew-cask
git pull
brew cask install healthi
```

**Comment by zeke** [comment]
Cool. Just needs a rebase!

**Comment by pablopunk** [comment]
@zeke nice! Btw I'm having problems here with conflicts, I thought I resolved them but it seems that I didn't 🤕

**Comment by zeke** [comment]
No worries. Here's some info about how to bring your fork up to date: https://help.github.com/articles/syncing-a-fork/

**Comment by pablopunk** [comment]
@zeke Yeah I did that, but when I pushed I got another conflict. It looks like when I was resolving the conflicts someone added another app 😂 
All solved now 👍

**Comment by zeke** [comment]
🎉 🍕

**Pull request merged**
