### PR TITLE
Update apps.yml

### PR DESCRIPTION
**Pull request by Cwoodall6**
I am the owner of the app. Thank you for the opportunity to showcase my work! I apologize if I did it wrong this is my first time doing this :).

### CODE REVIEW

**Comment by jlord** [comment]
Wow, cool! This looks super handy. Thanks!

**Comment by simonhochrein** [comment]
@Cwoodall6 There is no icon for this app

**Comment by Cwoodall6** [comment]
How do I add the icon png to the icon folder?

**Comment by Cwoodall6** [comment]
Do i need to add it from terminal?

**Comment by jlord** [comment]
Woah, whoops! I went to the repo and saw the icon there and totally missed that it wasn't in the PR. Sorry about that!

@Cwoodall6 Can you add the icon the the `images/apps` folder and make another PR?

**Pull request merged**
