### PR TITLE
Filtered appslist, new featured app and counter for apps in _apps.json

### PR DESCRIPTION
**Pull request by db2k**
# This Pullrequest adds

### Counter on top of apps list with the total amount of apps
image

### Sorted applist by publishdate and reversed for loop
image

### CODE REVIEW

**Comment by PterPmnta** [comment]
@db2k I hope add this filter date, is great!!!

**Comment by db2k** [comment]
Thanks, looking forward. Maybe there is some refactoring left, otherwise I prefer this sorting instead of alphabetic sorting.

**Comment by db2k** [comment]
I also have a preview here:
http://db2k.github.io/electron.atom.io/apps/

**Comment by 50Wliu** [comment]
(Note: not actively involved in Electron)

This looks nice, but I feel like the decision to make Discord a featured app is entirely unrelated to this PR and should be added in a separate pull request.

**Comment by db2k** [comment]
@50Wliu I agree, I'll revert that asap and do it seperated in a new PR also with an explanation why Discord should be included in the **featured apps** list.

**Comment by db2k** [comment]
@50Wliu I reverted the change and readded marp again.

**Comment by zeke** [comment]
This looks great @db2k. Thanks!

And thanks to @50Wliu for helping keep this PR focused. 👍

**Comment by PterPmnta** [comment]
@db2k  Great!!! thanks fot that, this solved that problem, when add to the oficial page?

**Comment by db2k** [comment]
@PterPmnta it's already online! :)
http://electron.atom.io/apps

**Comment by db2k** [comment]
Going to be even better because of #704

**Pull request merged**
