### PR TITLE
Add Medis

### PR DESCRIPTION
**Pull request by dinowang**

### CODE REVIEW

**Comment by jlord** [comment]
Thanks for adding this to the site! Just want to double check that you're involved with the project (we want to make sure someone from the project is OK with it being added)?

**Comment by dinowang** [comment]
Hi jlord,
No. I am not involved in Medis project. 
Just a user's suggestion.

**Comment by luin** [comment]
Thanks @dinowang for adding Medis! I'm the author of Medis and I'd like to see it shows up on the site. 😆

**Comment by MarshallOfSound** [comment]
@luin I'll reopen the PR for you then 😆 👍

**Comment by MarshallOfSound** [comment]
Actually with the conflicts it may be easier just to recreate the PR 😆

**Comment by zeke** [comment]
Thanks for submitting this app!

To make it easier for our team to review and verify the quality of app submissions, we've moved all the app metadata to a new repository. See [github.com/electron/electron-apps#adding-your-app](https://github.com/electron/electron-apps#adding-your-app) for info on how to open a new pull request there. Sorry for the inconvenience, and thanks again for taking the time to submit your app. For more info on the motivation behind this change, see this pull request: https://github.com/electron/electron.atom.io/pull/616

**Pull request closed without merging**
