### PR TITLE
I'm trying to add my app but I can't see it

### PR DESCRIPTION
**Pull request by DracotMolver**
Hi. I want to add my app, I've followed all the step but nothing happen. I've made a pull request, I've edited the yaml file and I've upload the image. What am I doing wrong?

### CODE REVIEW

**Comment by simonhochrein** [comment]
Please wait for your pull request to be merged

**Comment by DracotMolver** [comment]
ooh thanks for reply ^_^.

2016-09-20 17:25 GMT-03:00 simonhochrein <notifications@github.com>:

**Comment by zeke** [comment]
@DracotMolver it looks like your changes to the yml file are not included in this PR. Try editing the files on your fork and pushing up the changes.

**Comment by DracotMolver** [comment]
I edited the yml file twice...but nothing. I will do ti again. Thanks @zeke

**Comment by jlord** [comment]
Looks like you got it sorted out. Thanks @DracotMolver! It's live now: http://electron.atom.io/apps/

**Comment by DracotMolver** [comment]
@jlord Yes, thanks guys!!. You are amazing :)

**Pull request merged**
