### PR TITLE
[WIP] Internationalize

### PR DESCRIPTION
**Pull request by zeke**
This is a work in progress to make it possible to translate the Electron website into different languages. Any and all feedback on how to make this easier is welcome.

See the larger picture at https://github.com/electron/electron.atom.io/issues/686

Also watching this PR for inspiration: https://github.com/github/open-source-guide/pull/295 

## Jekyll i18n Implementation

This PR uses the [untra/polyglot](https://github.com/untra/polyglot) Jekyll plugin to enable internationalization:

> Polyglot is a fast, painless, open-source internationalization plugin for Jekyll blogs. Polyglot is easy to setup and use with any Jekyll project, and it scales to the languages you want to support. With fallback support for missing content, automatic url relativization, and powerful SEO tools, Polyglot allows any multi-language jekyll blog to focus on content without the cruft.

See a minimal example of how Polyglot works [here](https://github.com/zeke/jekyll-polyglot-test).

## Locale

This PR is currently following suit with https://github.com/github/open-source-guide/pull/295 in its locale naming scheme, meaning we're using the full-length [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag) for every locale, e.g. `en-US` vs `en`. 
Alternatively, we could use a mixture of "primary language subtag" for languages like English, then only use the qualifying local as needed, e.g. `zh-CN` and `zh-TW`

Any thoughts on this, @alebourne?

## TODO

- [x] Create a structure for localizing strings (`_data/en-US/locale.yml`)
- [ ] Update all strings in the markup
- [ ] Figure out structure for translating the guides themselves
- [ ] Add locale switcher on the site
- [ ] Complete one translation to make sure the infrastructure is sufficient. We're planning to start with Spanish, as it is a language our team can comfortably vet.

cc @alebourne @bkeepers @electron/maintainers

### CODE REVIEW

**Comment by zeke** [comment]
🇪🇸 🇲🇽 🇦🇷 🇧🇴 🇨🇱 🇨🇴 🇨🇷 🇨🇺 🇩🇴 🇪🇨 🇸🇻 🇬🇶 🇬🇹 🇭🇳 🇳🇮 🇵🇦 🇵🇾 🇵🇪 🇵🇷 🇺🇾 🇻🇪 

screen shot 2017-02-21 at 3 12 43 pm

**Comment by bkeepers** [comment]
This is awesome! I'd be curious to see how you like the [jekyll-polyglot](https://github.com/untra/polyglot) plugin.

**Comment by sotayamashita** [comment]
@zeke I also have commented github/opensource.guide#359 and We are creating tool called [GitLocalize](https://gitlocalize.com/) to solve problem that @webknjaz commented ingithub/opensource.guide#288 below:

> there's additional concern, which bothers me for a while: fixes or improvements to original articles go to this repo and there's no way to automatically confirm that translated version still corresponds original one.

If you have any help to integrate GitLocalize, please feel free to ask me via sota@locki.io. :smile:

**Comment by jhabdas** [comment]
Here's how it was done for healthcare.gov (at least initially) https://developmentseed.org/blog/multilingual-jekyll-sites/

**Comment by zeke** [comment]
Thanks for sharing, @jhabdas 👍

**Comment by jhabdas** [comment]
No problem. Was looking at the Yarn website too briefly. So many different implementations. Good for innovation, bad for reuse :)~

**Comment by jhabdas** [comment]
@zeke np. i imagine you've already seen the yarn website and what they're doing, right? if not, take a peek: https://github.com/yarnpkg/website

**Comment by jhabdas** [comment]
besides the free third-party translation service, they're also using netlify to host their [jamstack](https://jamstack.org/). afiak netlify doesn't have the kind of UI [cloudcannon](http://cloudcannon.com/) does, they like cloudcannon they may allow unlimited worry-free plugin support for Jekyll

**Comment by zeke** [comment]
Fast-tracking this so we can get those YML locale strings imported into to our translation tool. I will report back here when that is ready for public use.

**Pull request merged**
