### PR TITLE
New productivity tool: Shortexts

### PR DESCRIPTION
**Pull request by CarlosR2**
New productivity tool: Shortexts

Submitted by main developer.

http://shortexts.com/

### CODE REVIEW

**Comment by Haacked** [comment]
Looks good to me. Thanks! :sparkles:

**Comment by zeke** [comment]
> It is because this is not downloaded from the App Store. By default OSX only allows to run apps downloaded from the app store.

@CarlosR2 this is not correct. To prevent users from seeing the "unidentified developer" warning, you just need to code sign your app. See these links for more info:

- http://electron.atom.io/docs/tutorial/mac-app-store-submission-guide/
- https://github.com/electron-userland/electron-osx-sign
- https://github.com/electron-userland/electron-builder

**Comment by CarlosR2** [comment]
yeah,

I wrote that weeks ago when I hadn't signed the app yet and didnt know about the developer program.
Now it's signed so I'll correct it.

thanks for the comment

**Comment by zeke** [comment]
👍

**Pull request merged**
