### PR TITLE
add electron-samples post

### PR DESCRIPTION
**Pull request by zeke**
@kevinsawicki created these nice little apps for the Hackbright hackathon at HQ last week.

Why not share them with the world? 🌏 

Rendered: https://github.com/electron/electron.atom.io/blob/15b24ea213f277be744570569b4a9b5d393315a5/_posts/2016-12-27-electron-samples.md

### CODE REVIEW

**Comment by zeke** [comment]
cc @kevinsawicki @groundwater -- feel free to expound, revise, etc.

**Comment by kevinsawicki** [comment]
Thanks for writing this up.

I'd like to flush out the readme a bit more in that repo before announcing it.

Also would probably want to move it under the Electron org,rename to `simple-samples`, and add a `CONTRIBUTING.md` as well.

**Comment by zeke** [comment]
Sounds good.

**Comment by zeke** [comment]
@kevinsawicki if you wanna move the repo to the electron org I can take care of the rest.

**Comment by zeke** [comment]
This is ready to go, pending https://github.com/electron/simple-samples/pull/1

Let's ship it tomorrow morning, Pacific time.

**Pull request merged**
