### PR TITLE
Catch contents aren't subcategory of docs

### PR DESCRIPTION
**Pull request by pierreneter**
Like: https://electron.atom.io/docs/glossary/
All: https://github.com/electron/electron-i18n/tree/master/content/en-US/docs /*.md

### CODE REVIEW

**Comment by pierreneter** [comment]
Rebased, can check at: https://electron-website-pr-811.herokuapp.com/docs/glossary

**Comment by zeke** [comment]
Sweet! Can you add a quick test for /docs/glossary ?

**Comment by pierreneter** [comment]
Sure.

**Comment by zeke** [comment]
🚀

**Pull request merged**
