### PR TITLE
Update apps.yml

### PR DESCRIPTION
**Pull request by scgm11**
fixed issues

### CODE REVIEW

**Comment by zeke** [comment]
@scgm11 I think this PR can be closed, as it looks like https://github.com/electron/electron.atom.io/pull/456 already landed.

**Comment by scgm11** [comment]
it was reverted

**Comment by zeke** [comment]
Oh, I see. In that case, are you able to make the necessary updates and resubmit, like @jlord asked in https://github.com/electron/electron.atom.io/pull/456#issuecomment-244431419?

**Comment by scgm11** [comment]
done this should be mergeable!

**Comment by scgm11** [comment]
not yet, some minutes I correct all

**Comment by zeke** [comment]
@scgm11 it looks like some old content (Wagon app) crept back into the PR. I opened a new one here for you: https://github.com/electron/electron.atom.io/pull/466

**Pull request closed without merging**
