### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by englishextra**

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
I think something went wrong with this PR, you need to change the apps file as well 👍

**Comment by englishextra** [comment]
Isnt it this https://github.com/englishextra/electron.atom.io/pull/1

**Comment by MarshallOfSound** [comment]
@englishextra That PR is from your fork to your fork.  You need to change the target to this repository

**Comment by englishextra** [comment]
Ok does the icon pass through,

**Comment by MarshallOfSound** [comment]
@englishextra I raised a PR for you with the correct target.  See #546

**Comment by zeke** [comment]
Landed in #546 instead.

**Pull request closed without merging**
