### PR TITLE
Add Pexels to electron.atom.io/apps

### PR DESCRIPTION
**Pull request by brunjo**
Added Pexels to apps.yml

### CODE REVIEW

**Comment by zeke** [comment]
Looks nice.

**Comment by jlord** [comment]
This `.png` has that same weird Safari bug where it is a gif haha, see: https://github.com/electron/electron.atom.io/pull/412

@brunjo would you mind saving it again as a `.png`?

**Comment by brunjo** [comment]
Thanks @jlord. That's a strange bug. I exported it again and it works now.

**Comment by jlord** [comment]
Nice, thanks!

**Comment by zeke** [comment]
🌀

**Pull request merged**
