### PR TITLE
Move apps to data file

### PR DESCRIPTION
**Pull request by jc00ke**
Easier to update the list now.

Also fixed the app descriptions, so you can read what the app is w/o having to click the link.

### CODE REVIEW

**Comment by jc00ke** [comment]
If this is merged then #157, #231, #233 and #234 might want to rebase and update their PRs too.

**Comment by mnquintana** [comment]
Would you mind making this a JSON or YAML file? CSV is quite unwieldy and difficult to maintain.

**Comment by kevinsawicki** [comment]
This was done as part of the Electron 10 relaunch that just happened and was merged in #238 

There is now an `apps.yml` file that powers http://electron.atom.io/apps/

Thanks for opening this but I think we are all set now and I'm going to close this out. Apologies for the delayed response and thanks for contributing :shipit:

**Comment by jc00ke** [comment]
Will you accept a PR that adds the description into the title attribute? IMO while it's nice one can see the name of the app, this new design still suffers from the same problem... I have to click on the link to find out what the app does.

**Comment by kevinsawicki** [comment]
> Will you accept a PR that adds the description into the title attribute? 

Yup, that would be great, thanks.

**Pull request closed without merging**
