### PR TITLE
Add app description to title attr in app grid

### PR DESCRIPTION
**Pull request by jc00ke**
Revamped #237

### CODE REVIEW

**Comment by kevinsawicki** [comment]
This looks good to me, @simurai @jlord any concerns?

**Comment by simurai** [comment]
I like it too. 👍 

But maybe have name + description in the title? `{{ app.name }} - {{ app.description }}`.  So that apps with very long names are still shown somewhere.

screen shot 2016-05-12 at 3 27 49 pm

**Comment by kevinsawicki** [comment]
> But maybe have name + description in the title? 

Yeah, good point, @jc00ke would you mind incorporating that?

**Comment by jc00ke** [comment]
Sure, I actually had it that way originally but removed the app name. Will adjust shortly.

**Comment by simurai** [comment]
Looks good! 🚢  Thanks @jc00ke

**Comment by jc00ke** [comment]
Thank you!

**Pull request merged**
