### PR TITLE
Add HyperTerm to apps list

### PR DESCRIPTION
**Pull request by Meadowcottage**
Adding [HyperTerm](https://hyperterm.org/) to apps list.

### CODE REVIEW

**Comment by jlord** [comment]
Awesome, HyperTerm rules! Just want to get @rauchg's OK though before we add it.

**Comment by rauchg** [comment]
👌🙇

**Comment by rauchg** [comment]
Thanks @Meadowcottage

**Comment by Meadowcottage** [comment]
No problem. No harm in adding it to the list. The more the merrier 😄

**Comment by jlord** [comment]
Awesome, thanks @rauchg ( 👋 ! ) and @Meadowcottage!

**Pull request merged**
