### PR TITLE
Adding TIDAL to the list of Electron apps

### PR DESCRIPTION
**Pull request by andymartinwork**

### CODE REVIEW

**Comment by zeke** [comment]
Thanks @andymartinwork!

I can see on your GitHub profile that you work at TIDAL, but just to be sure that we have the okay to publish this, I emailed `press` and `advertising` at your domain for approval. No disrespect, just want to make sure we're in the clear.

cc @Haacked who is excited about TIDAL 🎷

**Comment by Haacked** [comment]
jayz-clap

**Comment by andymartinwork** [comment]
No problems, that's a good idea! I will try and make sure things are ok on this end too.

**Comment by zeke** [comment]
@andymartinwork I haven't heard from anyone yet. Anyone you can ping? ☎️

**Comment by andymartinwork** [comment]
Sure thing, we are having a discussion on the media policy of our development team at the moment. There might be a delay.

**Comment by zeke** [comment]
Landed at https://github.com/electron/electron-apps/pull/2

**Pull request closed without merging**
