### PR TITLE
Add quickcalcicon

### PR DESCRIPTION
**Pull request by Cwoodall6**

### CODE REVIEW

**Comment by jlord** [comment]
✨

**Comment by Cwoodall6** [comment]
Did I do something wrong? Its still not showing. Sorry if I'm being a pain.

**Comment by jlord** [comment]
@Cwoodall6 Nope, it is there:

screen shot 2016-09-23 at 4 06 23 pm

**Comment by Cwoodall6** [comment]
Yeah I have no idea whats going on
screen shot 2016-09-23 at 7 13 01 pm

**Comment by Haacked** [comment]
@Cwoodall6 hmm, maybe do a hard refresh. Which browser?

**Comment by Cwoodall6** [comment]
Yeah I don't know what was going on, but all is well now.

**Pull request merged**
