### PR TITLE
add app hardinfo

### PR DESCRIPTION
**Pull request by foozzi**

### CODE REVIEW

**Comment by zeke** [comment]
Hi. This PR needs an icon file.

**Comment by foozzi** [comment]
@zeke uploaded and edit file.

**Comment by zeke** [comment]
I like the icon. 👍 

The description reads a little funny. Maybe something like "Collect and share information about your computer's hardware". 

Also, this needs a rebase before it can be merged.

Thanks!

**Comment by foozzi** [comment]
@zeke good idea! i'm edit description

**Comment by zeke** [comment]
Nice. Just needs a rebase now.

**Comment by foozzi** [comment]
@zeke sorry, how can I do it?

**Pull request closed without merging**
