### PR TITLE
Add Chrysalis Music

### PR DESCRIPTION
**Pull request by ubunturox104**
Adding the Chrysalis Music app, which my "company" created.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
To clarify, this appears to be a clone of vincelwt's [Harmony](https://github.com/vincelwt/harmony) music player with a new icon and a slightly modified UI?

Can you possibly clarify exactly what you added or changed / what makes it different?

**Comment by ubunturox104** [comment]
As of right now, that's what it seems like. However, I do plan to implement more features into the software, such as integration with (if possible) Pandora, custom themes, voice control, a better Material Design look-and-feel, integration with a custom music service, sharing options, and better metadata controls. After all, this is Beta 2; more changes will come in the future.

**Comment by zeke** [comment]
Please note somewhere in the README that your project is a fork of Harmony, and we will gladly feature it here.

Also, it looks like you need to rebase as some other PRs have landed since you opened yours.

Thanks!

**Comment by zeke** [comment]
Closing this due to inactivity. Feel free to re-open if you're still interested in featuring your app.

**Pull request closed without merging**
