### PR TITLE
Invitation

### PR DESCRIPTION
**Pull request by mathematic-alpha**
There is an emerging community of developers in my country now and it will be a great opportunity to have you here :).

### CODE REVIEW

**Comment by zeke** [comment]
Does your group have a website?

**Comment by mathematic-alpha** [comment]
Nope we are still like grouping up to make a strong thing but I guess if needed, we can create one soon as well as having an irc channel.

**Comment by zeke** [comment]
Maybe you can just do `mailto:someone` as an href for now?

**Comment by mathematic-alpha** [comment]
I have been learning stuffs in web dev but my aim was to be able to use it to make desktop apps. Luckily, I found electron and since I have been working on it. I told others and they were like ooff ( no C and java again) :)

**Comment by mathematic-alpha** [comment]
I don't understand what you mean by mailto:someone

**Comment by zeke** [comment]
Every community listed on https://electron.atom.io/community/#meetups has a link to that group. Since you don't have a website yet, you could just do this:

```yml
href: 'mailto:mathalpha26@gmail.com'
```

This means your group will include a link so people can email to find out more about it.

**Comment by mathematic-alpha** [comment]
Oh I see

**Comment by mathematic-alpha** [comment]
I will edit and make a PR

**Comment by mathematic-alpha** [comment]
i will close this one

**Pull request closed without merging**
